export const demoData = [
    {
        id: 1,
        title: "Personal Style 01",
        img: '/storage/images/home/dashboards/personal1.png',
        desc: "For personal usage and reports",
        category: "dashboard",
        url: "/dashboards/personal-1",
    },
    {
        id: 2,
        title: "Personal Style 02",
        img: '/storage/images/home/dashboards/personal2.png',
        desc: "For personal usage and reports",
        category: "dashboard",
        url: "/dashboards/personal-2",
    },
    {
        id: 3,
        title: "Personal Style 03",
        img: '/storage/images/home/dashboards/personal3.png',
        desc: "For personal usage and reports",
        category: "dashboard",
        url: "/dashboards/personal-3",
    },
    {
        id: 4,
        title: "Analytics",
        img: '/storage/images/home/dashboards/analytics.png',
        desc: "Analytics and data visualization",
        category: "dashboard",
        url: "/dashboards/analytics",
    },
    {
        id: 5,
        title: "Stock Management",
        img: '/storage/images/home/dashboards/stock.png',
        desc: "For managing stock and inventory",
        category: "dashboard",
        url: "/dashboards/stock",
    },
    {
        id: 6,
        title: "Sales Dashboard",
        img: '/storage/images/home/dashboards/sales.png',
        desc: "Dashboard for tracking sales performance",
        category: "dashboard",
        url: "/dashboards/sales",
    },
    {
        id: 7,
        title: "Banking Style 01",
        img: '/storage/images/home/dashboards/banking1.png',
        desc: "Dashboard for banking operations",
        category: "dashboard",
        url: "/dashboards/banking-1",
    },
    {
        id: 8,
        title: "Banking Style 02",
        img: '/storage/images/home/dashboards/banking2.png',
        desc: "Dashboard for banking operations",
        category: "dashboard",
        url: "/dashboards/banking-2",
    },
    {
        id: 9,
        title: "Banking Style 03",
        img: '/storage/images/home/dashboards/banking3.png',
        desc: "Dashboard for banking operations",
        category: "dashboard",
        url: "/dashboards/banking-3",
    },
    {
        id: 10,
        title: "Flight Tracking",
        img: '/storage/images/home/dashboards/flight.png',
        desc: "Dashboard for tracking flight information",
        category: "dashboard",
        url: "/dashboards/flights",
    },
    {
        id: 11,
        title: "Company Overview",
        img: '/storage/images/home/dashboards/company.png',
        desc: "Dashboard providing an overview of company data",
        category: "dashboard",
        url: "/dashboards/company",
    },
    {
        id: 12,
        title: "HR Dashboard",
        img: '/storage/images/home/dashboards/hr.png',
        desc: "Dashboard for managing human resources",
        category: "dashboard",
        url: "/dashboards/hr",
    },
    {
        id: 13,
        title: "Course Dashboard",
        img: '/storage/images/home/dashboards/course.png',
        desc: "Dashboard for managing courses and education",
        category: "dashboard",
        url: "/dashboards/course",
    },
    {
        id: 14,
        title: "Jobs Dashboard",
        img: '/storage/images/home/dashboards/jobs.png',
        desc: "Dashboard for tracking job-related information",
        category: "dashboard",
        url: "/dashboards/jobs",
    },
    {
        id: 15,
        title: "Influencer Dashboard",
        img: '/storage/images/home/dashboards/influencer.png',
        desc: "Dashboard for influencers and social media management",
        category: "dashboard",
        url: "/dashboards/influencer",
    },
    {
        id: 16,
        title: "Hobbies Dashboard",
        img: '/storage/images/home/dashboards/hobbies.png',
        desc: "Dashboard for tracking personal hobbies and interests",
        category: "dashboard",
        url: "/dashboards/hobbies",
    },
    {
        id: 17,
        title: "Health Dashboard",
        img: '/storage/images/home/dashboards/health.png',
        desc: "Dashboard for monitoring health and fitness",
        category: "dashboard",
        url: "/dashboards/health",
    },
    {
        id: 18,
        title: "Writer Dashboard",
        img: '/storage/images/home/dashboards/writer.png',
        desc: "Dashboard for writers and content creators",
        category: "dashboard",
        url: "/dashboards/writer",
    },
    {
        id: 19,
        title: "Video Dashboard",
        img: '/storage/images/home/dashboards/video.png',
        desc: "Dashboard for video content creators",
        category: "dashboard",
        url: "/dashboards/video",
    },
    {
        id: 20,
        title: "Soccer Dashboard",
        img: '/storage/images/home/dashboards/soccer.png',
        desc: "Dashboard for soccer and sports enthusiasts",
        category: "dashboard",
        url: "/dashboards/soccer",
    },
    {
        id: 21,
        title: "E-commerce Dashboard",
        img: '/storage/images/home/dashboards/ecommerce.png',
        desc: "Dashboard for managing e-commerce operations",
        category: "dashboard",
        url: "/dashboards/ecommerce",
    },
    {
        id: 22,
        title: "Food Dashboard",
        img: '/storage/images/home/dashboards/food.png',
        desc: "Dashboard for food and culinary enthusiasts",
        category: "dashboard",
        url: "/dashboards/food-delivery",
    },
    {
        id: 23,
        title: "Map Style 01",
        img: '/storage/images/home/dashboards/map1.png',
        desc: "Map-themed dashboard style",
        category: "dashboard",
        url: "/dashboards/maps-style-01",
    },
    {
        id: 24,
        title: "Map Style 02",
        img: '/storage/images/home/dashboards/map2.png',
        desc: "Map-themed dashboard style",
        category: "dashboard",
        url: "/dashboards/maps-style-02",
    },
    {
        id: 25,
        title: "Inbox Dashboard",
        img: '/storage/images/home/dashboards/inbox.png',
        desc: "Dashboard for managing messages and communication",
        category: "dashboard",
        url: "/dashboards/inbox",
    },
    {
        id: 26,
        title: "Messaging Dashboard",
        img: '/storage/images/home/dashboards/messaging.png',
        desc: "Dashboard for real-time messaging",
        category: "dashboard",
        url: "/dashboards/messaging",
    },
    {
        id: 27,
        title: "Apex Charts",
        img: '/storage/images/home/dashboards/apexcharts.png',
        desc: "Dashboard showcasing Apex Charts integration",
        category: "widgets",
        url: "/apex-charts",
    },
    {
        id: 28,
        title: "UI Widgets",
        img: '/storage/images/home/dashboards/uiwidgets.png',
        desc: "Dashboard featuring UI widget components",
        category: "widgets",
        url: "/ui-widgets",
    },
    {
        id: 29,
        title: "Creative Widgets",
        img: '/storage/images/home/dashboards/creativewidgets.png',
        desc: "Dashboard showcasing creative and custom widgets",
        category: "widgets",
        url: "/creative-widgets",
    },
    {
        id: 30,
        title: "List Widgets",
        img: '/storage/images/home/dashboards/listwidgets.png',
        desc: "Dashboard featuring list-style widgets",
        category: "widgets",
        url: "/list-widgets",
    },
    {
        id: 31,
        title: "List Style 01",
        img: '/storage/images/home/dashboards/list1.png',
        desc: "For list views and collections",
        category: "lists",
        url: "/list-01",
    },
    {
        id: 32,
        title: "List Style 02",
        img: '/storage/images/home/dashboards/list2.png',
        desc: "For list views and collections",
        category: "lists",
        url: "/list-02",
    },
    {
        id: 33,
        title: "List Style 03",
        img: '/storage/images/home/dashboards/list3.png',
        desc: "For list views and collections",
        category: "lists",
        url: "/list-03",
    },
    {
        id: 34,
        title: "List Style 04",
        img: '/storage/images/home/dashboards/list4.png',
        desc: "For list views and collections",
        category: "lists",
        url: "/list-04",
    },
    {
        id: 35,
        title: "Flex Style 01",
        img: '/storage/images/home/dashboards/flex1.png',
        desc: "For flex views and collections",
        category: "lists",
        url: "/flex-01",
    },
    {
        id: 36,
        title: "Flex Style 02",
        img: '/storage/images/home/dashboards/flex2.png',
        desc: "For flex views and collections",
        category: "lists",
        url: "/flex-02",
    },
    {
        id: 37,
        title: "Flex Style 03",
        img: '/storage/images/home/dashboards/flex3.png',
        desc: "For flex views and collections",
        category: "lists",
        url: "/flex-03",
    },
    {
        id: 38,
        title: "Table Style 01",
        img: '/storage/images/home/dashboards/table1.png',
        desc: "For table views and collections",
        category: "lists",
        url: "/table-01",
    },
    {
        id: 39,
        title: "Table Style 02",
        img: '/storage/images/home/dashboards/table2.png',
        desc: "For table views and collections",
        category: "lists",
        url: "/table-02",
    },
    {
        id: 40,
        title: "Table Style 03",
        img: '/storage/images/home/dashboards/table3.png',
        desc: "For table views and collections",
        category: "lists",
        url: "/table-03",
    },
    {
        id: 41,
        title: "Company Form",
        img: '/storage/images/home/dashboards/companyform.png',
        desc: "Form for company information",
        category: "forms",
        url: "/company-layout",
    },
    {
        id: 42,
        title: "Doctor Form",
        img: '/storage/images/home/dashboards/doctorform.png',
        desc: "Form for medical professionals",
        category: "forms",
        url: "/doctor-layout",
    },
    {
        id: 43,
        title: "Checkout Form",
        img: '/storage/images/home/dashboards/checkoutform.png',
        desc: "Form for completing a purchase",
        category: "forms",
        url: "/checkout-layout",
    },
    {
        id: 44,
        title: "Event Form",
        img: '/storage/images/home/dashboards/eventform.png',
        desc: "Form for event registration",
        category: "forms",
        url: "/event-layout",
    },
    {
        id: 45,
        title: "Password Generator",
        img: '/storage/images/home/dashboards/passwordgen.png',
        desc: "Tool for generating secure passwords",
        category: "forms",
        url: "/password-gen",
    },
    {
        id: 46,
        title: "Meeting Form",
        img: '/storage/images/home/dashboards/meetingform.png',
        desc: "Form for scheduling meetings",
        category: "forms",
        url: "/meeting-layout",
    },
    {
        id: 47,
        title: "Place Load Style 01",
        img: '/storage/images/home/dashboards/placeload1.png',
        desc: "Place loading animation style",
        category: "placeloads",
        url: "/placeload-01",
    },
    {
        id: 48,
        title: "Place Load Style 02",
        img: '/storage/images/home/dashboards/placeload2.png',
        desc: "Place loading animation style",
        category: "placeloads",
        url: "/placeload-02",
    },
    {
        id: 49,
        title: "Place Load Style 03",
        img: '/storage/images/home/dashboards/placeload3.png',
        desc: "Place loading animation style",
        category: "placeloads",
        url: "/placeload-03",
    },
    {
        id: 50,
        title: "Place Load Style 04",
        img: '/storage/images/home/dashboards/placeload4.png',
        desc: "Place loading animation style",
        category: "placeloads",
        url: "/placeload-04",
    },
    {
        id: 51,
        title: "Grid list 01",
        img: '/storage/images/home/dashboards/grid1.png',
        desc: "For showing grid data",
        category: "layouts",
        url: "/card-grid-01",
    },
    {
        id: 52,
        title: "Grid list 02",
        img: '/storage/images/home/dashboards/grid2.png',
        desc: "For showing grid data",
        category: "layouts",
        url: "/card-grid-02",
    },
    {
        id: 53,
        title: "Grid list 03",
        img: '/storage/images/home/dashboards/grid3.png',
        desc: "For showing grid data",
        category: "layouts",
        url: "/card-grid-03",
    },
    {
        id: 54,
        title: "Grid list 04",
        img: '/storage/images/home/dashboards/grid4.png',
        desc: "For showing grid data",
        category: "layouts",
        url: "/card-grid-04",
    },
    {
        id: 55,
        title: "Tile 01",
        img: '/storage/images/home/dashboards/tile1.png',
        desc: "For showing tiles data ",
        category: "layouts",
        url: "/tile-01",
    },
    {
        id: 56,
        title: "Tile 02",
        img: '/storage/images/home/dashboards/tile2.png',
        desc: "For showing tiles data ",
        category: "layouts",
        url: "/tile-02",
    },
    {
        id: 57,
        title: "Tile 03",
        img: '/storage/images/home/dashboards/tile3.png',
        desc: "For showing tiles data ",
        category: "layouts",
        url: "/tile-03",
    },
    {
        id: 58,
        title: "User 01",
        img: '/storage/images/home/dashboards/user1.png',
        desc: "For showing user card",
        category: "layouts",
        url: "/user-grid-01",
    },
    {
        id: 59,
        title: "User 02",
        img: '/storage/images/home/dashboards/user2.png',
        desc: "For showing user card",
        category: "layouts",
        url: "/user-grid-02",
    },
    {
        id: 60,
        title: "User 03",
        img: '/storage/images/home/dashboards/user3.png',
        desc: "For showing user card",
        category: "layouts",
        url: "/user-grid-03",
    },
    {
        id: 61,
        title: "User 04",
        img: '/storage/images/home/dashboards/user4.png',
        desc: "For showing user card",
        category: "layouts",
        url: "/user-grid-04",
    },
    {
        id: 62,
        title: "Project 01",
        img: '/storage/images/home/dashboards/project1.png',
        desc: "For showing project card",
        category: "projects",
        url: "/project-01",
    },
    {
        id: 63,
        title: "Project 02",
        img: '/storage/images/home/dashboards/project2.png',
        desc: "For showing project card",
        category: "projects",
        url: "/project-02",
    },
    {
        id: 64,
        title: "Project 03",
        img: '/storage/images/home/dashboards/project3.png',
        desc: "For showing project card",
        category: "projects",
        url: "/project-03",
    },
    {
        id: 65,
        title: "Project Details",
        img: '/storage/images/home/dashboards/projectdetails.png',
        desc: "For showing project card",
        category: "projects",
        url: "/project-details",
    },
    {
        id: 66,
        title: "Kanban",
        img: '/storage/images/home/dashboards/kanban.png',
        desc: "Kanban board",
        category: "projects",
        url: "/kanban-board",
    },
    {
        id: 67,
        title: "Login 01",
        img: '/storage/images/home/dashboards/login1.jpg',
        desc: "Login form",
        category: "authentication",
        url: "/login-1",
    },
    {
        id: 68,
        title: "Login 02",
        img: '/storage/images/home/dashboards/login2.jpg',
        desc: "Login form",
        category: "authentication",
        url: "/login-2",
    },
    {
        id: 69,
        title: "Login 03",
        img: '/storage/images/home/dashboards/login3.jpg',
        desc: "Login form",
        category: "authentication",
        url: "/login-3",
    },
    {
        id: 70,
        title: "Login 04",
        img: '/storage/images/home/dashboards/login4.jpg',
        desc: "Login form",
        category: "authentication",
        url: "/login-4",
    },
    {
        id: 71,
        title: "Signup 01",
        img: '/storage/images/home/dashboards/signup1.jpg',
        desc: "Signup form",
        category: "authentication",
        url: "/signup-1",
    },
    {
        id: 72,
        title: "Signup 02",
        img: '/storage/images/home/dashboards/signup2.jpg',
        desc: "Signup form",
        category: "authentication",
        url: "/signup-2",
    },
    {
        id: 73,
        title: "Signup 03",
        img: '/storage/images/home/dashboards/signup3.jpg',
        desc: "Signup form",
        category: "authentication",
        url: "/signup-3",
    },
    {
        id: 74,
        title: "Forgot",
        img: '/storage/images/home/dashboards/forgot.jpg',
        desc: "Forgot password form",
        category: "authentication",
        url: "/forgot-password",
    },
    {
        id: 75,
        title: "OTP",
        img: '/storage/images/home/dashboards/otp.jpg',
        desc: "Otp input form",
        category: "authentication",
        url: "/code-verification",
    },
    {
        id: 76,
        title: "Reset",
        img: '/storage/images/home/dashboards/reset.jpg',
        desc: "Reset Password form",
        category: "authentication",
        url: "/reset-password",
    },
    {
        id: 77,
        title: "Checkmail",
        img: '/storage/images/home/dashboards/checkmail.jpg',
        desc: "Check email page",
        category: "authentication",
        url: "/check-mail",
    },
    {
        id: 78,
        title: "Profile",
        img: '/storage/images/home/dashboards/profile.png',
        desc: "For showing user profile",
        category: "profile",
        url: "/profile",
    },
    {
        id: 79,
        title: "Edit Profile",
        img: '/storage/images/home/dashboards/editprofile.png',
        desc: "For edit user profile",
        category: "profile",
        url: "/edit-profile",
    },
    {
        id: 80,
        title: "Notifications",
        img: '/storage/images/home/dashboards/notifications.png',
        desc: "Notification page",
        category: "profile",
        url: "/notifications",
    },
    {
        id: 81,
        title: "Settings",
        img: '/storage/images/home/dashboards/settings.png',
        desc: "Settings page",
        category: "profile",
        url: "/settings",
    },
    {
        id: 82,
        title: "Search Result",
        img: '/storage/images/home/dashboards/searchresult.png',
        desc: "For showing search result",
        category: "profile",
        url: "/search-results",
    },
    {
        id: 83,
        title: "Empty Search",
        img: '/storage/images/home/dashboards/emptysearch.png',
        desc: "For showing empty search result",
        category: "profile",
        url: "/empty-search",
    },
    {
        id: 84,
        title: "SASS Billing",
        img: '/storage/images/home/dashboards/sassbilling.png',
        desc: "Sass bililng form",
        category: "profile",
        url: "/sass-billing",
    },
    {
        id: 85,
        title: "Action 01",
        img: '/storage/images/home/dashboards/action1.png',
        desc: "Action page",
        category: "wizard",
        url: "/action-page-1",
    },
    {
        id: 86,
        title: "Action 02",
        img: '/storage/images/home/dashboards/action2.png',
        desc: "Action page",
        category: "wizard",
        url: "/action-page-2",
    },
    {
        id: 87,
        title: "Confirm Account",
        img: '/storage/images/home/dashboards/confirm.png',
        desc: "Login form",
        category: "wizard",
        url: "/confirm-account",
    },
    {
        id: 88,
        title: "Promotion",
        img: '/storage/images/home/dashboards/promotion.png',
        desc: "Promotion page",
        category: "wizard",
        url: "/promotion",
    },
    {
        id: 89,
        title: "Invoice",
        img: '/storage/images/home/dashboards/invoice.png',
        desc: "For print and download invoice ",
        category: "wizard",
        url: "/invoice",
    },
    {
        id: 90,
        title: "Service Status",
        img: '/storage/images/home/dashboards/servicestatus.png',
        desc: "For showing service status",
        category: "wizard",
        url: "/service-status",
    },
    {
        id: 91,
        title: "System Error",
        img: '/storage/images/home/dashboards/503.png',
        desc: "For showing error page",
        category: "wizard",
        url: "/system-error",
    },
    {
        id: 92,
        title: "Two Factor",
        img: '/storage/images/home/dashboards/twofactor.png',
        desc: "Two factor authentication page",
        category: "onboarding",
        url: "/two-factor",
    },
    {
        id: 93,
        title: "Plan",
        img: '/storage/images/home/dashboards/plan.png',
        desc: "Pricing plan",
        category: "onboarding",
        url: "/plan-boarding",
    },
    {
        id: 94,
        title: "Role",
        img: '/storage/images/home/dashboards/role.png',
        desc: "Role selection options",
        category: "onboarding",
        url: "/role-selection",
    },
];
